### ISSUE TITLE
It does not work well with HTTP::Client

### ISSUE THREAD

**Issue by samflores** [icy-arctic-fox/spectator#1] opened 2019-08-21 23:08 UTC
I'm trying to test a class that makes a HTTP GET request using Spectator. The previous test, using stdlib's `spec`, works just fine and running the application is also successful, but when using Spectator it fails.

Here's a reduced case that fails:

```ruby
require "spectator"
require "http"

Spectator.describe "something" do
  it "makes a request" do
     url = "http http://httpbin.org/deflate "
     body = HTTP::Client.get(url).body
     expect(body).not_to be_nil
  end
end
```
Upon running `crystal spec` I get the following error:
```
Module validation failed: !dbg attachment points at wrong subprogram for function
!10 = distinct !DISubprogram(name: "initialize", linkageName: "initialize", scope: !5, file: !5, line: 115, type: !6, scopeLine: 115, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2)
void (%"OpenSSL::BIO"*, %TCPSocket*)* @"*OpenSSL::BIO#initialize<TCPSocket>:Nil"
  %2 = call i8** @"~OpenSSL::BIO::CRYSTAL_BIO:read"(), !dbg !12
!12 = !DILocation(line: 14, column: 5, scope: !13)
!13 = distinct !DISubprogram(name: "set_data", linkageName: "set_data", scope: !5, file: !5, line: 13, type: !6, scopeLine: 13, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2)
!13 = distinct !DISubprogram(name: "set_data", linkageName: "set_data", scope: !5, file: !5, line: 13, type: !6, scopeLine: 13, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2)
 (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

Any idea what might be causing it?

**Comment by icy-arctic-fox** [comment] 2019-08-22 00:17
Not sure yet what the cause is, but I'm still investigating. It could be a bug in the compiler, but I will see if there's anything in Spectator I can do to work around it.

It appears that running `crystal spec --debug` and `crystal spec --release` do not produce this error. But I have reproduced this by just running `crystal spec` with Crystal 0.30.1.

Output from when using `--debug`:
```
E

Failures:

  1) something makes a request
     Error: flate: invalid stored block lengths

       Flate::Error: flate: invalid stored block lengths
         /usr/share/crystal/src/flate/reader.cr:112:13 in 'unbuffered_read'
         /usr/share/crystal/src/io/buffered.cr:79:16 in 'read'
         /usr/share/crystal/src/io.cr:554:29 in 'gets_to_end'
         /usr/share/crystal/src/http/client/response.cr:81:15 in 'consume_body_io'
         /usr/share/crystal/src/http/client/response.cr:105:9 in 'from_io?'
         /usr/share/crystal/src/http/client.cr:581:5 in 'exec_internal_single'
         /usr/share/crystal/src/http/client.cr:567:5 in 'exec_internal'
         /usr/share/crystal/src/http/client.cr:563:5 in 'exec'
         /usr/share/crystal/src/http/client.cr:685:5 in 'exec'
         /usr/share/crystal/src/http/client.cr:717:7 in 'exec'
         /usr/share/crystal/src/http/client.cr:389:3 in 'get'
         spec/test_spec.cr:7:13 in '__temp_54'
         spec/test_spec.cr:5:3 in 'run_instance'
         lib/spectator/src/spectator/runnable_example.cr:74:11 in 'run_example'
         lib/spectator/src/spectator/runnable_example.cr:64:9 in '->'
         lib/spectator/src/spectator/runnable_example.cr:255:3 in 'run_wrapper'
         lib/spectator/src/spectator/runnable_example.cr:45:9 in 'capture_result'
         lib/spectator/src/spectator/runnable_example.cr:12:7 in 'run_impl'
         lib/spectator/src/spectator/example.cr:26:7 in 'run'
         lib/spectator/src/spectator/internals/harness.cr:29:7 in 'run'
         lib/spectator/src/spectator/runner.cr:60:18 in 'run_example'
         lib/spectator/src/spectator/runner.cr:35:9 in 'collect_results'
         lib/spectator/src/spectator/runner.cr:356:5 in 'run'
         lib/spectator/src/spectator.cr:113:5 in 'run'
         lib/spectator/src/spectator.cr:87:29 in '->'
         /usr/share/crystal/src/kernel.cr:255:3 in 'run'
         /usr/share/crystal/src/crystal/main.cr:47:5 in 'main'
         /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
         __libc_start_main
         _start
         ???

     # spec/test_spec.cr:5

Finished in 156.03 milliseconds
1 examples, 1 failures, 1 errors, 0 pending

Failed examples:

crystal spec spec/test_spec.cr:5 # something makes a request
```

**Comment by icy-arctic-fox** [comment] 2019-08-22 00:34
`--no-debug` works as well. There are multiple issues in the Crystal repository on this:
https://github.com/crystal-lang/crystal/issues/6920
https://github.com/crystal-lang/crystal/issues/5656
Exact issue in Crystal: https://github.com/crystal-lang/crystal/issues/7060

But it looks like there is a workaround that could be put into Spectator. Will look into it.

**Comment by icy-arctic-fox** [comment] 2019-08-22 00:58
Changed the spec code to this and it worked flawlessly with no extra arguments.

```crystal
require "http" # <--- HTTP included before Spectator.
require "spectator"

Spectator.describe "something" do
  it "makes a request" do
     url = "http://httpbin.org/deflate"
     body = HTTP::Client.get(url).body
     expect(body).not_to be_nil
  end
end
```

Idea came from this comment: https://github.com/crystal-lang/crystal/issues/7060#issuecomment-438575289

**Comment by icy-arctic-fox** [comment] 2019-08-22 01:36
There's a workaround in the latest version - 0.8.2. Let me know if this works for you or anything else pops up.

**Comment by samflores** [comment] 2019-08-22 11:49
Awesome! Both the compilation flags and the 0.8.2 version work for me. Thank you.

**Comment by icy-arctic-fox** [comment] 2019-08-22 13:00
No problem! Hopefully the Crystal devs find a way to fix this in the compiler.

Closing this issue. Please comment again if the issue manifests in another form, or open a new issue if you have any other problems. I'd be glad to help.

**Closed as completed by icy-arctic-fox** 2019-08-22 13:00 UTC
Labels: bug
